"""Central German UI wording for FloatNotes."""

APP_NAME = "FloatNotes"
FLOATING_ICON_TITLE = "FloatNotes Launcher"
FLOATING_ICON_TOOLTIP = "FloatNotes öffnen oder ausblenden"

LOCAL_NOTES = "Lokale Notizen"
LISTS = "Listen"
NEW_LIST = "Neue Liste"
RENAME = "Umbenennen"
DELETE = "Löschen"
EDIT = "Bearbeiten"
ADD = "Hinzufügen"
CANCEL = "Abbrechen"
SAVE = "Speichern"
CREATE = "Erstellen"
OPEN = "Öffnen"
HIDE = "Ausblenden"
QUIT = "Beenden"
READY = "Bereit"

NO_LIST_SELECTED = "Keine Liste ausgewählt"
ALL_NOTES_LOCAL = "Alle Notizen werden lokal gespeichert."
NO_LISTS_TITLE = "Noch keine Listen"
NO_LISTS_HELP = (
    "Erstelle links eine neue Liste. Deine Daten bleiben offline auf diesem Windows-Benutzerkonto."
)
NO_NOTES = "Keine Notizen vorhanden."
EMPTY_LIST_HELP = "Diese Liste ist leer. Füge unten den ersten Stichpunkt hinzu."
NEW_TASK_PLACEHOLDER = "Neue Aufgabe..."
ALL_DONE = "✓ Alles erledigt"
TASKS_META = "{total} Aufgaben  ·  {completed} erledigt  ·  lokal gespeichert"
OPEN_TASKS = "{count} offen"
STORAGE_LOCATION = "Speicherort: {path}"

CREATE_LIST_TITLE = "Neue Liste"
CREATE_LIST_MESSAGE = "Wie soll die neue Notizen-Liste heißen?"
RENAME_LIST_TITLE = "Liste umbenennen"
RENAME_LIST_MESSAGE = "Passe den Namen der ausgewählten Liste an."
DELETE_LIST_TITLE = "Liste löschen"
DELETE_LIST_CONFIRM = "Liste löschen"
DELETE_LIST_MESSAGE = "Liste '{name}' und alle enthaltenen Aufgaben dauerhaft löschen?"

EDIT_TASK_TITLE = "Aufgabe bearbeiten"
EDIT_TASK_MESSAGE = "Ändere den Text dieser Aufgabe."
DELETE_TASK_TITLE = "Aufgabe löschen"
DELETE_TASK_CONFIRM = "Aufgabe löschen"
DELETE_TASK_MESSAGE = "Aufgabe '{text}' dauerhaft löschen?"

LIST_NAME_EMPTY = "Listenname darf nicht leer sein."
TASK_TEXT_EMPTY = "Stichpunkt darf nicht leer sein."
LIST_SAVED = "Liste gespeichert."
LIST_RENAMED = "Liste umbenannt."
LIST_DELETED = "Liste gelöscht."
LISTS_SORTED = "Listen sortiert."
TASK_SAVED = "Stichpunkt gespeichert."
TASK_UPDATED = "Stichpunkt aktualisiert."
TASK_DELETED = "Stichpunkt gelöscht."
TASKS_SORTED = "Aufgaben sortiert."
STATUS_SAVED = "Status gespeichert."
STORAGE_ERROR_TITLE = "Speicherfehler"
STORAGE_FAILED = "Speichern fehlgeschlagen."

SHOW_FLOATING_ICON = "Floating-Icon anzeigen"

AUTOSTART_ENABLE = "Autostart aktivieren"
AUTOSTART_DISABLE = "Autostart deaktivieren"
AUTOSTART_UNAVAILABLE = "Autostart nicht verfügbar"
AUTOSTART_TITLE = "Autostart"
AUTOSTART_DISABLE_QUESTION = "FloatNotes nicht mehr automatisch beim Windows-Start ausführen?"
AUTOSTART_DISABLED = "Autostart wurde deaktiviert."
AUTOSTART_BUILD_REQUIRED = "Autostart ist erst nach dem EXE-Build verfügbar."
AUTOSTART_ENABLE_QUESTION = "FloatNotes beim Windows-Start automatisch starten?\n\nZiel:\n{target}"
AUTOSTART_ENABLED = "Autostart wurde aktiviert."
